server:
  port: 8234


spring:
  application:
    name: henan-culture
  jpa:
    hibernate:
      ddl-auto: update      # 请自行修改 请自行修改 请自行修改
    open-in-view: false     # 关闭 OSIV

  #  datasource本地配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/culture?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: d2505283c6c17866
    driver-class-name: com.mysql.cj.jdbc.Driver

  #  redis本地配置 请自行配置
  redis:
    database: 10
    host: 127.0.0.1
    port: 6379

#  微信小程序配置 appid /appsecret
wx:
  applet:
    appid: wx6f9e0b5e9fec4791
    appsecret: 22ce9e8b63540b5822788bdd778378f8

game:
  prefix: wx_culture